// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.2
// 	 protoc        v3.20.1
// source: cosmos/feegrant/index.ts

import * as feegrant from "./_export";
export { feegrant };
