// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.2
// 	 protoc        v3.20.1
// source: cosmos/base/reflection/v2alpha1/index.ts

import * as v2alpha1 from "./_export";
export { v2alpha1 };
