// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.2
// 	 protoc        v3.20.1
// source: ibc/applications/transfer/index.ts

import * as transfer from "./_export";
export { transfer };
