// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.2
// 	 protoc        v3.20.1
// source: ibc/core/client/v1/index.ts

import * as v1 from "./_export";
export { v1 };
