// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v0.4.0
//   protoc        v3.21.7

import { Writer, Reader, Protobuf } from "as-proto";

export class Any {
  static encode(message: Any, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.typeUrl);

    writer.uint32(18);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): Any {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Any();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.typeUrl = reader.string();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  typeUrl: string;
  value: Uint8Array;

  constructor(typeUrl: string = "", value: Uint8Array = new Uint8Array(0)) {
    this.typeUrl = typeUrl;
    this.value = value;
  }
}

export function encodeAny(message: Any): Uint8Array {
  return Protobuf.encode(message, Any.encode);
}

export function decodeAny(buffer: Uint8Array): Any {
  return Protobuf.decode<Any>(buffer, Any.decode);
}
