name: Test

on: push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: git submodule update --init --force
      - run: yarn install --frozen-lockfile
      - run: yarn test
